/**
 * MUSEUM DATA
 * Edit this file to update all ePortfolio content.
 * The 3D museum reads from this data to populate exhibits.
 */

const MUSEUM_DATA = {
    coverLetter: {
        title: "Welcome",
        buildContent: function() {
            return '' +
            /* ---- Hook ---- */
            '<p style="text-align:center; font-size:1.8rem; font-weight:bold; color:#e8d5b7; font-family:Georgia,serif; line-height:1.3; font-style:italic; letter-spacing:0.02em; margin:0 0 1rem;">' +
                'We can learn a lot about humans from dead birds.' +
            '</p>' +

            /* ---- Section 1: text, then pics below ---- */
            '<p style="margin:0 0 1rem;">Not <em>those</em> birds, rather the extinct kind: dinosaurs. A particularly poignant example is Sue the <em>Tyrannosaurus Rex</em>. She is a skeleton of scars. Lumps on her ribs. An oversized leg bone. Punctured holes on her lower jaw. These oddities on her bones are not superficial marks but deep-rooted pains forgotten for 67 million years and only rediscovered by chance in the South Dakota Badlands. Broken ribs. An infected fibula. Holes of the parasitic infection trichomonosis\u2026 eventually leading to death by starvation. These scars tell a tale of struggles and downfalls that seem too much to bear.</p>' +
            '<div style="display:flex; gap:0.75rem; margin-bottom:1rem;">' +
                '<div style="flex:1; text-align:center;">' +
                    '<img src="assets/images/welcome_letter/pic1_2.png" style="width:100%; border-radius:4px; display:block;">' +
                    '<p style="margin:0.4rem 0 0; font-size:0.9rem; color:#a89b8c; font-style:italic;">Me with Sue in 2016</p>' +
                '</div>' +
                '<div style="flex:1; text-align:center;">' +
                    '<img src="assets/images/welcome_letter/pic1_3.png" style="width:100%; border-radius:4px; display:block;">' +
                    '<p style="margin:0.4rem 0 0; font-size:0.9rem; color:#a89b8c; font-style:italic;">Me with Sue in 2025</p>' +
                '</div>' +
            '</div>' +

            /* ---- Section 2: full-width text ---- */
            '<p style="margin:0 0 1rem;">Growing up in the quiet village of Skokie, Illinois, the prolonging dullness of my childhood was quelled by the excitement I found in dinosaurs. What began as fascination transformed into curiosity: not just <em>what</em> happened to them, but <em>how</em> bodies record trauma and adapt to survive. Through fossils, I learned to read bones as narratives of resilience, vulnerability, and life.</p>' +

            /* ---- Section 3: pic2 left, text right ---- */
            '<div style="display:flex; gap:1rem; margin-bottom:1rem;">' +
                '<div style="flex:0 0 35%;">' +
                    '<img src="assets/images/welcome_letter/pic2.png" style="width:100%; border-radius:4px; display:block;">' +
                '</div>' +
                '<div style="flex:1; display:flex; flex-direction:column; justify-content:center;">' +
                    '<p style="margin:0 0 0.6rem;">That curiosity eventually turned inward.</p>' +
                    '<p style="margin:0 0 0.6rem;">If ancient bones could reveal so much about pain and survival, what could living bodies teach us?</p>' +
                    '<p style="margin:0;">This question drew me toward the human body and ultimately to medicine \u2014 not to study anatomy and physiology in isolation but to understand people through their stories.</p>' +
                '</div>' +
            '</div>' +

            /* ---- Section 4: full-width text ---- */
            '<p style="margin:0 0 1rem;">I first entered Stanford University as a strict pre-medical student, but after my experience as a Hoover Student Fellow at the Hoover Institution studying research security, I became further captivated by the intertwined nature of science, technology, and law for real societal effects. Since then, I have pursued opportunities in science to learn discovery, engineering to learn technical skills, and international security to learn deployment of innovation to benefit the greater public. Throughout these experiences, it has only become more evident to me the power of communication in bridging gaps between disparate stakeholders as a means to combine forces for the greatest impact possible.</p>' +

            /* ---- Section 5: two images side by side ---- */
            '<div style="display:flex; gap:0.8rem; margin-bottom:1rem;">' +
                '<div style="flex:1;">' +
                    '<img src="assets/images/welcome_letter/pic3.png" style="width:100%; display:block; border-radius:4px;">' +
                '</div>' +
                '<div style="flex:1;">' +
                    '<img src="assets/images/welcome_letter/pic4.png" style="width:100%; display:block; border-radius:4px;">' +
                '</div>' +
            '</div>' +

            /* ---- Section 6: closing text ---- */
            '<p style="margin:0;">My goal in pursuing the Notation in Science Communication is to learn and reflect on how to become a better advocate of science and technology. I believe no field is truly isolated and that recognizing the interdisciplinarity of the world is the key for future progress, just like how Sue communicated to me how to become a better human.</p>' +

            '<div style="margin-top:1.5rem; padding:1rem 1.2rem; background:rgba(201,169,110,0.1); border:1px solid rgba(201,169,110,0.3); border-radius:8px;">' +
                '<h3 style="color:#c9a96e; margin:0 0 0.5rem; font-size:1.1rem;">How to Navigate This Museum</h3>' +
                '<p style="margin:0 0 0.6rem;">Close this letter by clicking the <strong>X</strong> in the top-right corner or pressing <strong>ESC</strong>. From there, you have two ways to explore:</p>' +
                '<p style="margin:0 0 0.4rem;"><strong>1. Walk through the museum.</strong> Use <strong>WASD</strong> or the <strong>arrow keys</strong> to move and the <strong>mouse</strong> to look around, just like walking through a real museum. Click on any framed artifact on the walls to read about it.</p>' +
                '<p style="margin:0;"><strong>2. Use the Museum Map.</strong> Press <strong>M</strong> at any time to open the map, which lists every artifact in the museum. Click any item to jump directly to it, just like navigating a regular website. The map is always available, so you never have to walk anywhere if you prefer not to.</p>' +
            '</div>';
        }
    },

    aboutMe: {
        title: "About Me",
        content: '<div style="text-align:center; margin-bottom:1rem;">' +
            '<img src="assets/images/headshot_eportfolio.png" style="width:180px; height:180px; border-radius:50%; object-fit:cover; display:block; margin:0 auto; border:3px solid #c9a96e;">' +
            '</div>' +
            '<p>Hi! I\u2019m T. Matthew Kim, a senior at Stanford University from Irvine, California. I\u2019m pursuing a B.S. in Biology and Computer Science, a coterminal M.S. in Computer Science on the Artificial Intelligence track, Honors in International Security, and a Notation in Science Communication. In other words, I\u2019m interested in how science, technology, and policy can work together to drive responsible, impactful innovation.</p>' +
            '<p>That interest has taken me in a few directions. In research, I\u2019ve built ex-vivo perfusion systems for heart transplantation, performed endourologic research on kidney stones, and analyzed sycophancy in AI for healthcare. On the policy and security side, I\u2019ve researched international collaborations in science and technology at the Hoover Institution, prototyped medical AI systems for biosecurity and biodefense, and contributed to a course on security and privacy in bioinformatics.</p>' +
            '<p>This portfolio captures how I think about science communication \u2014 not just as a skill but as a practice that shapes how ideas move between disciplines, audiences, and communities.</p>' +
            '<p>My other interests include fossil collecting, origami, cubing, golfing, hiking, and traveling. Feel free to reach out at <a href="mailto:tmattkim@stanford.edu" style="color:#c9a96e;">tmattkim@stanford.edu</a> if you\u2019d like to connect!</p>'
    },

    aboutPortfolio: {
        title: "About This ePortfolio",
        content: '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Purpose</h3>' +
            '<p>This ePortfolio is the capstone project for my Notation in Science Communication (NSC) at Stanford University. It brings together nine artifacts spanning three thematic categories \u2014 Trilobite, Archaeopteryx, and Neanderthal \u2014 each accompanied by reflections on the rhetorical choices, audience considerations, and lessons learned during their creation. Together, they document my growth as a science communicator across multimedia, policy, and technical contexts.</p>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Design</h3>' +
            '<p>This ePortfolio is presented as an interactive 3D museum visitors can walk through, built with <strong>Three.js</strong> (r128). Each wing of the museum corresponds to a thematic category, and exhibits are displayed as framed artworks on the walls. The museum metaphor was chosen to evoke the experience of discovery and curation, reinforcing the idea that each artifact is a carefully placed exhibit in a larger narrative.</p>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Tech Stack</h3>' +
            '<div style="display:grid; grid-template-columns:1fr 1fr; gap:0.3rem 1.5rem; margin:0.5rem 0 1rem;">' +
                '<div><span style="color:#a89b8c;">3D Engine</span><br><strong>Three.js r128</strong></div>' +
                '<div><span style="color:#a89b8c;">Language</span><br><strong>Vanilla JavaScript</strong></div>' +
                '<div><span style="color:#a89b8c;">Styling</span><br><strong>CSS3</strong></div>' +
                '<div><span style="color:#a89b8c;">Markup</span><br><strong>HTML5</strong></div>' +
            '</div>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Typography</h3>' +
            '<p><strong>Georgia</strong> (serif) is used for headings, body text, and exhibit labels, chosen for its readability and classical tone. <strong>Helvetica Neue / Arial</strong> (sans-serif) is used for UI elements, controls, and captions. <strong>Monospace</strong> is used for keyboard hints and technical labels.</p>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Color Palette</h3>' +
            '<div style="display:flex; gap:0.6rem; flex-wrap:wrap; margin:0.5rem 0 1rem;">' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#1a1a2e; border:1px solid #555; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#1a1a2e<br>Background</span>' +
                '</div>' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#0e0e1a; border:1px solid #555; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#0e0e1a<br>Deep BG</span>' +
                '</div>' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#c9a96e; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#c9a96e<br>Gold Accent</span>' +
                '</div>' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#e8d5b7; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#e8d5b7<br>Headings</span>' +
                '</div>' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#a89b8c; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#a89b8c<br>Subtext</span>' +
                '</div>' +
                '<div style="text-align:center;">' +
                    '<div style="width:48px; height:48px; border-radius:6px; background:#f0e6d3; margin:0 auto 4px;"></div>' +
                    '<span style="font-size:11px; color:#a89b8c;">#f0e6d3<br>Body Text</span>' +
                '</div>' +
            '</div>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Photography</h3>' +
            '<p>All photos of fossils featured in this ePortfolio are from my personal collection or from my travels to museums and sites of paleontological significance.</p>' +

            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Acknowledgments</h3>' +
            '<p>Thank you to Dr. Katherine Rothschild, Dr. Kevin Moore, and Dr. Erin Mordecai for their incredible guidance, as well as all of my friends in the Notation in Science Communication program at Stanford who made this ePortfolio possible. I would also like to thank Dr. Ron Kopito, Dr. Pranav Rajpurkar, Dr. Mejgan Massoumi, and everyone else who has supported me on my academic adventure. A special shout out to my family who give me the strength to improve myself every day!</p>'
    },

    exhibits: {
        trilobite: {
            name: "Trilobite Wing",
            subtitle: "Reveal",
            color: 0x8B7355,
            description: "Over 500 million years ago, trilobites became the first organisms to develop complex, compound eyes, an evolutionary leap that transformed how life could perceive and interact with the world. What was once a blur of undifferentiated stimuli became structured, navigable information. The artifacts in this category represent that same transformative act: taking raw, dense, or abstract scientific information and rendering it into something perceptible and interpretable. Whether through data visualization, diagrammatic representation, or careful rhetorical framing, these works demonstrate my ability to give shape to complexity, making the invisible visible and the opaque legible for non-specialist audiences. Just as the trilobite's eyes did not create the world around it but revealed what was already there, these artifacts aim to clarify rather than simplify science.",
            artifacts: [
                {
                    title: "Paleostoric YouTube Video",
                    thumbnail: 'trilobite-0',
                    content: '<a href="https://www.youtube.com/watch?v=DSb_AsUHt-U" target="_blank" rel="noopener" style="display:block; position:relative; margin-bottom:1rem; border-radius:6px; overflow:hidden; cursor:pointer; text-decoration:none;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['trilobite-0'] ? EXHIBIT_THUMBNAILS['trilobite-0'] : 'https://img.youtube.com/vi/DSb_AsUHt-U/hqdefault.jpg') + '" style="width:100%; display:block; border-radius:6px;">' +
                        '<div style="position:absolute; top:0; left:0; width:100%; height:100%; display:flex; align-items:center; justify-content:center; background:rgba(0,0,0,0.3);">' +
                            '<div style="width:68px; height:48px; background:rgba(255,0,0,0.85); border-radius:12px; display:flex; align-items:center; justify-content:center;">' +
                                '<div style="width:0; height:0; border-left:18px solid #fff; border-top:11px solid transparent; border-bottom:11px solid transparent; margin-left:4px;"></div>' +
                            '</div>' +
                        '</div>' +
                        '<div style="position:absolute; bottom:0; left:0; right:0; padding:8px 12px; background:rgba(0,0,0,0.7); color:#ccc; font-size:13px;">Click to watch on YouTube</div>' +
                    '</a>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is my first video from Paleostoric, a YouTube channel I created during high school to share my fossil collection and build an online community of enthusiasts. Titled <em>A Rare Trilobite So Well Preserved It Looks Alive | Pyritized Trilobite</em>, the video showcases my pyritized <em>Triarthrus eatoni</em> trilobite from New York, which I acquired at the annual Tucson Fossil Showcase.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Communicating Science to a Broad Audience</h3>' +
                        '<p>My primary goal was accessibility. I wanted anyone, from a curious twelve-year-old to an adult with no paleontology background, to follow along and feel genuinely excited about the specimen. To achieve this, I minimized jargon, let close-up visuals of the fossil do much of the explanatory work, and structured the narrative around what makes this trilobite remarkable rather than burying the appeal under technical detail. As my first video, I also experimented with conventions common to the medium: an intro, an outro, B-roll footage, and background music. At the time, my decisions about pacing and arrangement were largely intuitive, guided more by what felt right than by any deliberate rhetorical strategy.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Learning from Analytics and Audience Feedback</h3>' +
                        '<p>Out of all my videos, this debut remains my most successful, with 22,097 views as of this writing. That reach brought something I had not initially anticipated: substantive feedback. Commenters pointed to specific areas for improvement, particularly audio quality and limiting distortion, technical elements I now realize directly affect how clearly science is communicated through multimedia.</p>' +
                        '<p>YouTube\u2019s analytics proved equally instructive. By examining where viewership dropped off, I discovered that the steepest decline occurred during an extended segment where I simply rotated the specimen on camera without narration or context. While editing, I had struggled to cut sections I felt attached to, but the data confirmed what I suspected on rewatching. Without purposeful framing, even a stunning fossil loses a viewer\u2019s attention.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This experience crystallized two principles I now carry into all my communicative work. First, audiences value their time, so every moment of a presentation should demonstrate why the content matters. Second, restraint strengthens impact. If I\u2019m debating whether to keep a section, it is almost always better to cut it and preserve only what resonates most. Together, these lessons have shaped how I think about rhetorical choices across formats, pushing me to prioritize clarity, engagement, and intentional design whenever I translate science for an audience.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "PaleoPals Storytelling Podcast",
                    thumbnail: 'trilobite-1',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['trilobite-1'] ? EXHIBIT_THUMBNAILS['trilobite-1'] : '') + '" style="max-width:280px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="https://drive.google.com/file/d/13m9hR8sR9TSti_s3LmDwL6VycsPPz3GR/view?usp=sharing" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Listen to the Podcast</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a podcast episode I produced for PWR 91KA (Science Storytelling for Kids) during the spring of my junior year. The open-ended assignment asked us to create a children\u2019s science podcast on any topic, giving us full creative control over format and execution. I designed the cover art and built the episode around two original characters: Mesozoic Matt and his sidekick, Clucky the Chicken.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Designing for a Specific Audience</h3>' +
                        '<p>I saw this project as a chance to revisit what I loved about making YouTube videos but in a purely audio medium with a much more precisely defined audience: children aged six to eight. That specificity forced me to think far more deliberately about structure and presentation than I had in previous work. During brainstorming, I kept returning to the shows I gravitated toward as a kid, such as <em>Dino Dan</em>, <em>Dinosaur Train</em>, <em>SpongeBob SquarePants</em>, and noticed a recurring device in programs like <em>Go, Diego, Go!</em>, <em>Dora the Explorer</em>, and <em>Blue\u2019s Clues</em>: the animal sidekick. That observation led me to create Clucky the Chicken as a companion to Mesozoic Matt. The pairing felt fitting given that chickens are living descendants of theropod dinosaurs, including the <em>Tyrannosaurus rex</em>, which allowed me to embed a real scientific connection directly into the show\u2019s premise. I also incorporated detective-style elements so that young listeners would feel as though they were being brought along on an investigative adventure.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Crafting Narrative Around Science</h3>' +
                        '<p>The most challenging part of the process was shaping paleontological content into a coherent storyline with genuine emotional stakes. Early drafts focused too heavily on delivering scientific information, which left the narrative flat. The in-class workshops, particularly the writers\u2019 room sessions where small groups brainstormed and critiqued each other\u2019s ideas, were instrumental in helping me rethink my approach. I shifted the center of gravity from the science itself to Clucky\u2019s personal arc: his journey from believing he is insignificant to realizing he descends directly from the survivors of the asteroid impact. The science became woven throughout that emotional thread rather than competing with it.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Using Music as a Rhetorical Tool</h3>' +
                        '<p>This project also marked a turning point in how I use music. Reflecting on my YouTube work, I recognized that I had placed background tracks somewhat haphazardly, without considering how they shape a listener\u2019s emotional response. For the podcast, I was much more intentional, selecting and timing music to mirror the characters\u2019 emotional journey so that listeners could feel the tension, wonder, and resolution alongside Clucky and Matt. The greatest lesson I took from this artifact is the power of evoking emotion to create lasting impact and that music is one of the most effective tools for doing so in an audio medium.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Feedback and Iteration</h3>' +
                        '<p>Peer feedback during the course highlighted specific areas I would still like to refine, including balancing audio levels at certain points and rewriting portions of the script to integrate scientific information more seamlessly. We also had the opportunity to share our podcasts with a class of fifth graders, who proved to be the harshest of critics. Several of them asked why the podcast felt \u201cso childish,\u201d which, rather than discouraging me, was actually reassuring. It confirmed that I had successfully calibrated the tone and complexity for my intended audience of six- to eight-year-olds rather than for older elementary students. That moment reinforced how much audience awareness matters and how even critical feedback can validate a deliberate rhetorical choice.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project deepened my understanding of three principles I continue to apply. First, narrative is the vehicle, not the obstacle. Science becomes more memorable and persuasive when it is embedded within a story audiences care about rather than presented as standalone information. Second, every production choice is a rhetorical choice. Music, pacing, and character design are not decorative but actively shape how an audience receives and feels the content. Third, defining a precise audience from the outset transforms every subsequent decision, from vocabulary and tone to narrative complexity. Real-world testing with that audience, even when the feedback stings, is the most reliable way to know whether those choices landed.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "<em>King Clucky</em> Children\u2019s Picture Book",
                    thumbnail: 'trilobite-2',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['trilobite-2'] ? EXHIBIT_THUMBNAILS['trilobite-2'] : '') + '" style="max-width:280px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="assets/docs/King_Clucky.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Read the Book (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a children\u2019s picture book I wrote and illustrated for PWR 91KA (Science Storytelling for Kids) during the spring of my junior year. The project tasked us with adapting our previous podcast project into either a science explainer video or a children\u2019s picture book. Having never worked in the picture book genre before, I chose that format and transformed the story of Clucky the Chicken, originally developed for my PaleoPals podcast, into a rhyming, illustrated narrative about the K-Pg extinction event and the evolutionary link between dinosaurs and birds.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Adapting Across Genres</h3>' +
                        '<p>A great challenge of this project was translating a story built for audio into one built for pages. In the podcast, Clucky\u2019s journey unfolded through dialogue between two characters (Mesozoic Matt and Clucky) supported by music, pacing, and vocal performance. A picture book has none of those tools. I needed to find a new structural engine, and the solution was replacing Mesozoic Matt with a narrator who speaks directly to both Clucky and the reader. This shift preserved the conversational, investigative quality of the original while taking advantage of something unique to picture books: the ability to break the fourth wall. The narrator\u2019s interjections (e.g., explaining the K-Pg boundary, pointing out iridium anomalies, revealing the Chicxulub crater, etc.) serve the same pedagogical function Mesozoic Matt did in the podcast, but the format allows the reader to feel addressed personally, creating a sense of shared discovery rather than passive listening.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Working Within the 32-Page Structure</h3>' +
                        '<p>Before this project, I had never considered that picture books follow a highly codified structure. The standard 32-page format imposes strict constraints on how much story can be told and how it must be paced. Learning this convention was itself a lesson in how genre shapes communication. What feels like a simple, effortless children\u2019s book is actually the product of careful architectural decisions about where to place emotional beats, when to turn the page, and how much information a single spread can carry. Looking back, I found that some of my pages were too text-heavy with rhyming couplets competing for space against the illustrations they were supposed to complement. I also recognize places where the vocabulary exceeds what a six- to eight-year-old would comfortably follow. The pages discussing iridium, for instance, introduce the word \u201celement\u201d without explanation, a term that most children in my target audience may not yet know. If I were to revise the book, I would cut certain explanatory passages, trust the illustrations to carry more of the informational weight, and simplify language wherever the rhyme scheme had led me toward precision at the expense of accessibility. The tension between wanting to include all the science and needing to respect both the format\u2019s constraints and the audience\u2019s developmental level mirrors a challenge I have encountered across nearly every project in my portfolio: knowing when to cut and when clarity for the audience matters more than fidelity to the source material.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Illustration as a Communicative Choice</h3>' +
                        '<p>Choosing to illustrate the book myself was a deliberate decision rooted in the kind of whimsical, hand-drawn aesthetic I wanted to evoke, something closer to the spirit of Dr. Seuss than to a polished digital production. Every illustration needed to do communicative work. The massive ancestry book dwarfing Clucky conveys the weight of his lineage without a word of exposition. The side-by-side comparison of the asteroid and Mount Everest makes scale immediately legible to a child. The silhouette of a <em>Tyrannosaurus rex</em> looming behind Clucky on the cover foreshadows the book\u2019s central revelation. I had no prior experience with picture book illustration, and the process taught me that visual storytelling in this genre is not decorative. Each image must advance the narrative, clarify the science, or deepen the emotional resonance of the text it accompanies.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Committing to Rhyme</h3>' +
                        '<p>I decided early on that the entire book would follow a rhyming scheme, inspired by the rhythmic, read-aloud quality of the picture books I loved as a child. This proved far more difficult than I anticipated. Maintaining consistent meter while also conveying accurate scientific information (e.g., the K-Pg boundary, iridium concentrations, shocked quartz, the Chicxulub crater, etc.) required constant negotiation between what sounded right and what was scientifically precise. In several places, the rhyme dictated word choices that I might not have made in prose, and I had to evaluate whether the resulting phrasing still communicated the concept clearly enough for a young reader. The exercise reinforced something I first learned while working on the podcast. Constraints on form are not obstacles to communication but generators of creative problem-solving, forcing the writer to find language that is simultaneously accurate, accessible, and aesthetically satisfying.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Embedding Personal Connections</h3>' +
                        '<p>The book is dedicated to Richard \u201cGussy,\u201d a fifth grader who had been one of the harshest critics of my podcast when we shared it with an elementary school class earlier in the quarter. Rather than treat his criticism as a setback, I chose to honor it, both in the dedication and (SPOILER ALERT!) by incorporating him as the narrator character, Gussy the Genius Boy, who reveals himself in the final pages. This decision served a dual purpose. It acknowledged the value of audience feedback, and it created a playful Easter egg that connected the book back to the real-world testing process that shaped its predecessor. The gesture also reflected something I have come to believe about science communication more broadly, that the best work is not produced in isolation but in dialogue with the people it is meant to reach.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project taught me three valuable lessons that go beyond children\u2019s literature. First, adapting content across genres is not a matter of transposition but of reinvention. The same story told through audio and through illustration requires fundamentally different structures, pacing, and rhetorical strategies, and the writer\u2019s job is to identify what each genre does best and rebuild the narrative around those strengths. Second, genre conventions like the 32-page picture book format are not arbitrary limitations but communicative frameworks that shape how an audience receives information, and learning to work within them is itself a form of rhetorical fluency. Third, illustration, like music, interactivity, and presentation slide design, is not supplementary to the message but constitutive of it. In a picture book, the drawings do not merely accompany the text but carry arguments of their own, and treating them as such transforms the entire communicative project.</p>',
                    reflection: null,
                    image: null
                }
            ]
        },
        archaeopteryx: {
            name: "Archaeopteryx Wing",
            subtitle: "Bridge",
            color: 0x6B8E6B,
            description: "<em>Archaeopteryx</em> represents one of the most crucial transitions in evolutionary history: the link between terrestrial dinosaurs and modern birds. It is an organism that belonged fully to neither world yet connected both. The artifacts in this category serve a similar function, bridging disciplinary boundaries, translating between expert and public audiences, and facilitating understanding across communities that might otherwise remain siloed. These works reflect the communicative challenge of operating at the threshold, which involves adapting tone, terminology, and rhetorical strategy to the needs of different contexts without sacrificing scientific rigor. Like <em>Archaeopteryx</em> itself, these artifacts do not simply exist in two worlds; they make passage between them possible, demonstrating that effective science communication is fundamentally an act of translation and distillation.",
            artifacts: [
                {
                    title: "Project Biosecurity",
                    thumbnail: 'archaeopteryx-0',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['archaeopteryx-0'] ? EXHIBIT_THUMBNAILS['archaeopteryx-0'] : '') + '" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="https://project-biosecurity.vercel.app/" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Play the Game</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is an interactive AI simulation game I built for PWR 91NSC (Introduction to Science Communication) during the autumn of my senior year. The assignment asked us to distill a literature review written earlier in the quarter into a \u201cpublic audience text.\u201d I chose to create a browser-based video game aimed at teenagers in which the player assumes the role of the President of the United States navigating a crisis involving AI-enabled bioweapons.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Translating Technical Research into an Immersive Experience</h3>' +
                        '<p>When I first began development, I worried the scope was too ambitious. Capturing the full breadth of my literature review, a dense paper on a weighty topic, across multiple scenes with coherent narrative progression felt overwhelming. Much of what ultimately shaped the project came from peer feedback and consulting sessions with Dr. Kath, and the rest of this reflection details the key decisions that emerged from that collaborative process.</p>' +
                        '<p>A central goal was immersion. My literature review addresses a timely subject driven by real-world developments, yet its technical register can distance readers from the urgency of the issue. Through iterative feedback, I discovered that immersion often hinges on small, deliberate details. Subtle design choices like the beeps punctuating each scene or smoother transition animations drew consistently positive responses and made gameplay more engaging. I also aimed to establish a serious tone, and one peer confirmed this had been achieved, describing the layout, fonts, and color palette as having an overall \u201csterile\u201d quality that suited the mission-driven subject matter.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Designing Meaningful Player Agency</h3>' +
                        '<p>Much of my focus went into the decision architecture, the branching scenes a player navigates. In my original version, every path led to the same failed outcome. After discussion with Dr. Kath, I reconsidered. While I had initially conceived the game as a commentary on a dire present-day situation, I came to believe that including a winnable path could offer hope while simultaneously demonstrating what effective policy steps might look like in the real world. The challenge was integrating that optimism without undermining the gravity of the topic.</p>' +
                        '<p>Rather than a simple win-or-lose binary, I implemented a scoring system tied to the player\u2019s actions and character interactions, leading to a spectrum of outcomes, including outright failure, a pyrrhic victory in which the crisis is resolved but at significant cost, and a genuinely successful resolution with its own associated reflection. This range, I hoped, would more realistically capture the complexity of navigating a biosecurity crisis and the varied futures such decisions could produce.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Building a Cast to Deepen Realism</h3>' +
                        '<p>Part of expanding the decision space meant adding more characters. My original version featured only the Presidential Daily Briefer and the National Security Council, referred to by title alone. I broadened the cast to include expert advisors, a CIA analyst, the National Security Advisor, the Secretary of State, and the Secretary of Defense, each given a name, a distinct color, and an icon. The CIA analyst, for instance, is Marcus Rivera, associated with green and a brain icon. These details served a dual purpose: they made interactions feel like conversations with real people rather than abstract institutions, and the visual associations helped players quickly identify who was speaking and what domain of expertise they represented.</p>' +
                        '<p>These new characters, in turn, opened up new narrative possibilities. The expert advisors enabled a consultation mechanic. For example, the Secretary of State and Secretary of Defense created branching paths toward diplomatic or military responses, respectively. Each addition reinforced the game\u2019s core rhetorical aim, letting players feel the weight and complexity of presidential decision-making during a crisis.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project taught me three lasting lessons. First, distilling and translating specialist research for a broad audience is not about simplifying. It is about finding the right vehicle, and an interactive simulation allowed me to preserve the complexity of my literature review while making it viscerally felt rather than passively read. Second, immersion lives in the details. Tone, sound design, color, and typography are not cosmetic but rhetorical choices that shape how seriously an audience engages with the content. Third, feedback is most powerful when it challenges foundational assumptions. The shift from a single failed outcome to a spectrum of endings fundamentally changed the message of the game, turning it from a warning into both a warning and an invitation to act.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "The Remotoscope",
                    thumbnail: 'archaeopteryx-1',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['archaeopteryx-1'] ? EXHIBIT_THUMBNAILS['archaeopteryx-1'] : '') + '" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="assets/docs/BIOE_70Q_Project_1.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Read the Paper (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a medical device innovation project completed for BIOE 70Q (Medical Device Innovation) during the spring of my sophomore year. The project followed the full biodesign process, from needs finding through prototyping, culminating in the Remotoscope: a goggle-mounted endoscope camera that allows physicians to examine a pediatric patient\u2019s ear canal and tympanic membrane hands-free, removing the need to physically restrain an uncooperative child during diagnosis.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Communicating Across Stakeholder Perspectives</h3>' +
                        '<p>A defining feature of this project was the breadth of stakeholder engagement required before any design work could begin. I conducted interviews with emergency physicians, pediatricians, parents of children with earaches, and individuals who recalled their own childhood experiences with ear pain. Each group surfaced different dimensions of the same problem. Physicians described the near-impossibility of getting a two-year-old to hold still for even two seconds with an otoscope. Parents spoke about their anxiety of middle-of-the-night emergency room visits. Former patients recalled fear and an inability to communicate what they were feeling. Synthesizing these perspectives required me to listen carefully for patterns across very different vocabularies and levels of technical understanding, a skill that mirrors the broader challenge of writing for audiences who do not share the same expertise.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Writing for Both Technical and Non-Technical Readers</h3>' +
                        '<p>The written report needed to serve dual audiences. On one hand, the project demanded precise technical language with terms like acute otitis media, tympanic membrane, and referred otalgia to communicate credibly within a bioengineering context. On the other hand, the needs-finding process and the device\u2019s rationale had to be accessible to anyone, including the non-specialist stakeholders whose insights shaped the design. I navigated this by grounding technical terms in plain-language explanations at their first appearance and by letting stakeholder voices carry much of the narrative. The physician interview, for instance, conveys complex diagnostic reasoning through concrete clinical scenarios rather than abstract medical terminology, making the information legible to engineers, parents, and clinicians alike.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Documenting the Design Process in Detail</h3>' +
                        '<p>One of the most important lessons from this project was the value of thorough documentation. The report traces every stage of prototyping. This includes building a benchtop ear model out of suturing rubber and tubing, testing three candidate materials for the camera housing, and iterating through multiple failed base designs before arriving at a working prototype. I documented each failure with photographs, explanations of what went wrong, and reasoning for what I tried next. This level of detail allows another engineer to understand not only what the final design looks like but why it looks that way, what alternatives were considered, and what trade-offs were made. Clear, thorough documentation transforms an individual prototyping experience into shared knowledge that others can build upon.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Iterative Problem-Solving as a Mode of Communication</h3>' +
                        '<p>The prototyping process itself became a form of argumentation. Each failed design (e.g., the chopstick lattice that slid along the endoscope, the craft sticks that buckled under tension, and the tongue depressor base that blocked the camera\u2019s field of view) served as evidence for the next design decision. By presenting the full sequence of iterations rather than just the final product, the report communicates not only a solution but a reasoning process. This approach mirrors how scientific arguments are built. Each claim rests on evidence from what came before, and transparency about setbacks strengthens rather than weakens the overall case.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project taught me three principles that extend well beyond bioengineering. First, the best solutions emerge from listening to the people closest to the problem. The needs-finding process showed me that stakeholder interviews surface insights no amount of literature review alone can provide, and communicating those insights faithfully is what gives a design its legitimacy. Second, writing for mixed audiences is not about choosing one level of complexity but about layering explanations so that both specialists and non-specialists can follow the same document without either feeling talked down to or left behind. Third, meticulous documentation is itself a communicative act. The care with which a process is recorded determines whether others can learn from it, replicate it, or improve upon it.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "AI-Driven Vaccine Allocation for the 2025 Texas Measles Outbreak",
                    frameTitle: "AI-Driven Vaccine Allocation for Measles",
                    thumbnail: 'archaeopteryx-2',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['archaeopteryx-2'] ? EXHIBIT_THUMBNAILS['archaeopteryx-2'] : '') + '" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="https://texasmeaslesai.github.io/" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px; margin-right:8px;">Visit the Website</a>' +
                        '<a href="assets/docs/BIO_176_Presentation.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">View the Slides (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is the final project for BIO 176 (Disease Ecology) during the fall of my senior year, investigating whether reinforcement learning, a type of AI that learns through trial and error, could outperform standard vaccine allocation strategies during the 2025 Texas measles outbreak. The project spanned two genres: a scientific presentation delivered to my class and an interactive public-facing website built using scrollytelling principles. The course offered three tracks for the final project (Science, Journalism, or Creative Expression), and I chose to combine the Science and Creative Expression tracks, pairing a rigorous computational investigation with an accessible, visually driven website.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Communicating to Two Different Audiences</h3>' +
                        '<p>The most significant challenge of this project was navigating two distinct genres for two distinct audiences simultaneously. The in-class presentation was aimed at my professor and peers, an audience deeply familiar with disease ecology concepts like SEIR models, R\u2080, and herd immunity thresholds, but likely unfamiliar with AI concepts such as reinforcement learning, Q-learning, and reward functions. The website, by contrast, was designed for a general public audience with potentially no background in either field. Each genre demanded different rhetorical strategies. The presentation could assume shared vocabulary around disease dynamics and focus its explanatory energy on the AI methodology while the website needed to build understanding from the ground up for both domains. Managing these parallel audiences reinforced how much the same content can require fundamentally different communicative approaches depending on who is receiving it.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Designing the Website as a Public Audience Text</h3>' +
                        '<p>For the website, I explored scrollytelling, a narrative technique in which content unfolds as the reader scrolls, blending text, visuals, and data into a guided experience. I wanted the site to feel clean, engaging, and interactive, so I made all figures responsive with hover features that allow readers to explore the data at their own pace rather than passively viewing static charts. I also maintained a consistent color scheme throughout to create visual coherence and signal professionalism. The headline \u201cCould AI Have Saved Texas From Measles?\u201d was a deliberate choice to draw in a non-specialist reader with a provocative question grounded in a real, timely event. Reflecting on the website now, I recognize that certain terms and variables could have been defined more carefully for readers with no prior knowledge of epidemiology or disease ecology. While the interactive elements aid comprehension, the explanatory scaffolding around the underlying science could be strengthened to make the site truly self-contained for any audience.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Presentation Under Constraints</h3>' +
                        '<p>The in-class presentation was originally designed for ten minutes but was reduced to five due to the number of students presenting. Rather than redesign my slides, I chose to keep the same deck and speak faster while cutting verbal explanation. In hindsight, this was not the best strategy. Several slides, particularly the one outlining all four vaccine allocation strategies together, became visually overwhelming without the narration they were designed to accompany. The dense information that worked in a ten-minute format felt rushed and hard to absorb at half the time. If I were to do it again, I would have cut down information on background information and disease ecology fundamentals since my audience already understood those concepts. I had included them partly to demonstrate my own mastery, but a more audience-aware approach would have trusted the shared knowledge in the room and allocated the limited time to the novel contribution: the AI methodology and its surprising results. This experience taught me that adapting a presentation to time constraints is not about speaking faster and requires making harder choices about what to include.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project solidified three lessons about scientific communication across genres. First, the same findings require genuinely different treatment for different audiences, not just different levels of simplification but different structures, entry points, and visual strategies. A scrollytelling website and a slide deck are not just two containers for the same content. They are two distinct arguments shaped by medium and audience. Second, interactivity is a powerful rhetorical tool for engagement, but it does not replace clear explanation. Interactive figures without sufficient context can leave a non-specialist audience impressed but confused. Third, constraints on time or space should be treated as opportunities to sharpen an argument, not obstacles to talk around. The willingness to cut content is itself a communicative skill and one I am still actively developing.</p>',
                    reflection: null,
                    image: null
                }
            ]
        },
        neanderthal: {
            name: "Neanderthal Wing",
            subtitle: "Build",
            color: 0x7B6B8E,
            description: "Neanderthals are our closest extinct relatives, so genetically proximate that 1–4% of the modern human genome still carries their legacy. However, they are gone, and we remain. Their story is not simply one of extinction but of near-persistence, a reminder that survival depends not just on capability but on adaptability, collaboration, and the capacity to build forward. The artifacts in this category engage with that forward-looking imperative. They represent my contributions to technological development and applied science communication in technical and professional contexts. Where the Trilobite reveals and the <em>Archaeopteryx</em> bridges, the Neanderthal builds. These pieces reflect on the tools, systems, and communicative practices that will shape the future of scientific work, and on the professional identity I am crafting as someone who does not just describe science but participates in its trajectory.",
            artifacts: [
                {
                    title: "PWR 91NSC Literature Review",
                    thumbnail: 'neanderthal-0',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['neanderthal-0'] ? EXHIBIT_THUMBNAILS['neanderthal-0'] : '') + '" style="max-width:280px; width:100%; border-radius:6px; display:block; margin:0 auto; box-shadow:0 2px 12px rgba(0,0,0,0.4);">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="assets/docs/PWR_91NSC_Literature_Review.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Read the Paper (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a literature review titled <em>Preventing the First Weapon of Mass Extinction: Addressing Artificial Intelligence for Bioweapons Development</em>, written for PWR 91NSC (Introduction to Science Communication) during the autumn of my senior year. The review examines the intersection of three disciplines \u2014 artificial intelligence, biosecurity, and international security theory \u2014 to argue that AI has fundamentally shifted the bioweapons threat landscape, making deterrence by denial and robust biodefense the only viable path forward. The paper was styled according to the submission guidelines of <em>International Security</em>, a leading journal in the field of international relations and security.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Writing Across Disciplinary Boundaries</h3>' +
                        '<p>The most formative challenge of this project was deciding who I was writing for. My topic sits at the convergence of three distinct discourse communities, each with its own conventions, vocabulary, and assumptions. Rather than writing exclusively for one, I chose to make the review accessible to all three, a deliberate rhetorical decision aimed at bridging gaps between disciplines that do not speak to one another enough. In practice, this meant defining terms that would be familiar to one community but opaque to another (i.e., explaining deterrence theory for an AI audience and explaining biological design tools for a security studies audience) and drawing from literature across all three fields to weave an interdisciplinary narrative. While I believe I largely succeeded, the only true test would be for members of each community to read the review and identify where clarity breaks down, a form of feedback I hope to seek out in the future.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Navigating a Rapidly Evolving Field</h3>' +
                        '<p>Synthesizing the literature itself proved unexpectedly difficult. I initially searched within the narrow scope of AI for biodefense, which returned very little. Broadening the framing to encompass AI\u2019s offensive and defensive roles in biosecurity opened up a much richer body of work but introduced a new problem: the field was evolving faster than I could write. Articles published only months apart contradicted one another, and breakthroughs regularly rendered earlier findings obsolete. For example, the National Academies assessed in April 2025 that biological design tools could not create self-replicating pathogens. By September 2025, a preprint had already disproven that claim. I had to make conscious, sometimes difficult choices about what to include and what to set aside, always asking whether a given development was necessary for the reader to follow the argument\u2019s logic.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Structuring the Argument</h3>' +
                        '<p>Grouping the literature into a coherent structure required extensive iteration. I treated the headers and subheaders as a working outline, testing different combinations of topics and orderings until I arrived at a progression that felt logical: AI\u2019s offensive capabilities, deterrence theory and its three camps, and finally the current state and critical gaps of AI for biodefense. This structure allowed me to build each section\u2019s argument on the foundation laid by the previous one, guiding the reader toward the review\u2019s central conclusion that patient-level AI biodefense represents an essential and neglected frontier.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Adopting Discipline Conventions</h3>' +
                        '<p>Styling the paper according to the submission guidelines of <em>International Security</em> was an exercise in a different kind of communication. The journal\u2019s formatting rules, from citation style and footnote conventions to heading hierarchy and manuscript structure, initially seemed like minor technicalities, but I realized adhering to them is what signals membership in a discourse community. Following these conventions is not just about \u201cgatekeeping.\u201d It facilitates communication by creating shared expectations between writer and reader. The process reinforced for me that discipline style is itself a rhetorical choice by telling the audience that the author understands and respects the norms of the conversation they are entering.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This literature review taught me three lessons I expect to carry well beyond this course. First, writing across disciplines requires deliberate translation work. This does not encompass simplification but the careful calibration of what to define, what to assume, and how to signal that multiple communities are being addressed simultaneously. Second, in a fast-moving field, the writer\u2019s job is not just to report findings but to curate them, making transparent choices about relevance and recency so that the argument remains coherent even as its underlying evidence shifts. Third, conventions matter more than they appear to. Adopting a journal\u2019s style is an act of rhetorical positioning that shapes how seriously an audience engages with the ideas presented.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "Medical AI Conference Workshop Paper",
                    thumbnail: 'neanderthal-1',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="assets/docs/healing_workshop_anthology_pic.png" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="https://aclanthology.org/2026.healing-1.2/" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">Read the Paper</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is my first published research paper, titled \u201cThe Doctor Will Agree With You Now: Sycophancy of Large Language Models in Multi-Turn Medical Conversations,\u201d accepted to the Linguistic Analysis for Health (HeaLing) Workshop at the European Chapter of the Association for Computational Linguistics (EACL) 2026. The paper evaluates sycophantic behavior, the tendency of AI models to conform to user beliefs rather than maintain factual accuracy, across ten large language models in multi-turn medical conversations. It also introduces a novel metric called Resistance to capture turn-by-turn stance dynamics.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">From Bootcamp to Publication</h3>' +
                        '<p>This paper was my first project with the Rajpurkar Lab at Harvard Medical School, completed as part of the Medical AI Bootcamp. In addition, it was my first experience navigating the full lifecycle of academic publication from experimental design to drafting to peer review to acceptance. Having a paper accepted and published online viewable by researchers worldwide through the ACL Anthology was a milestone that made the conventions of academic writing feel consequential rather than abstract. Every formatting choice, every claim\u2019s supporting evidence, and every figure\u2019s clarity mattered because they would be scrutinized by reviewers and read by an audience for potentially years to come.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Writing for a Specific Technical Audience</h3>' +
                        '<p>One of the most formative challenges was calibrating my writing for the workshop\u2019s particular audience. The HeaLing Workshop sits at the intersection of computational linguistics and healthcare, meaning readers would likely have deep expertise in natural language processing (NLP) but varying familiarity with clinical reasoning and medical literature, and vice versa. I had to make decisions about what to define and what to assume. For instance, I explained reinforcement learning from human feedback briefly for clinically oriented readers while assuming familiarity with standard NLP evaluation paradigms. This was my first experience writing for a specific technical discourse community with defined expectations around structure, citation style, and argumentation norms, and it sharpened my understanding of how the audience shapes every level of a paper from the abstract to the appendix.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Collaboration as Iterative Communication</h3>' +
                        '<p>The paper was deeply collaborative, involving co-authors from Harvard Medical School and the Scripps Research Institute. This required constant coordination, not just dividing tasks but iterating on shared prose, reconciling conflicting feedback, and ensuring that the narrative remained coherent as different voices contributed to it. A critical dimension was ensuring clinical validity. I worked closely with clinicians to verify that responses generated from our framework reflected realistic patient-physician dynamics, not just plausible-sounding prompts. I also sought feedback from researchers outside the lab to test whether the paper\u2019s contributions were clear to someone encountering the work for the first time. Through this process, I learned that scientific communication is not a one-time act but a constant iterative cycle. Each round of feedback revealed assumptions I had not realized I was making and refined the clarity of what we were trying to say.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Crafting a Narrative in Technical Writing</h3>' +
                        '<p>Working closely with my principal investigator and postdoctoral mentor, I learned that even highly technical papers need a clear narrative arc. Our paper does not simply report results. It is meant to tell a story from the real-world phenomenon of patients interacting with AI chatbots to the gap in existing evaluations to our multi-turn framework and its surprising findings about which models capitulate and why. My mentors pushed me to ensure that each section built logically on the previous one and that the reader always understood why a finding mattered, not just what the finding was. This was a fundamentally different kind of writing from anything I had done before. The argument had to be rigorous enough for peer review while remaining compelling enough that a busy researcher would want to keep reading.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Figures as the Paper\u2019s Backbone</h3>' +
                        '<p>One of the most valuable lessons was learning how technical figures should function as a self-contained summary of the paper\u2019s most important contributions. Our Resistance curves (Figures 2 and 3), the per-pushback drop visualizations, and the correctness-conditioned flip charts (Figure 4) were designed so that a reader could grasp the paper\u2019s core findings by examining the figures alone, a convention in top venues that I had not appreciated until working on this project. Designing these figures required careful thought about what to emphasize, what to omit, and how visual choices like color coding by model family or stacking cumulative drops could make complex multi-dimensional data immediately interpretable. The figures became a form of visual argumentation, and iterating on them taught me that data visualization is not supplementary to scientific writing. It is scientific writing.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project taught me three lessons that reshaped how I think about scientific communication. First, writing for a specific discourse community is an act of rhetorical positioning. The choices I made about vocabulary, structure, and citation signaled to reviewers that I understood the conversation I was entering, and getting those signals right was as important as the findings themselves. Second, collaboration demands that communication be treated as genuinely iterative. The paper improved not because any one person had the right answer but because each round of feedback from co-authors, clinicians, and external readers exposed blind spots and sharpened the argument. Third, in technical writing, narrative is not a luxury. It is what transforms a collection of experiments into a coherent contribution that readers can follow, evaluate, and build upon.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "Medical AI Conference Workshop Oral Presentation",
                    frameTitle: "Medical AI Oral Presentation",
                    thumbnail: 'neanderthal-2',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['neanderthal-2'] ? EXHIBIT_THUMBNAILS['neanderthal-2'] : '') + '" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="https://drive.google.com/file/d/1PxgnevA3bQeYb7zMjvtWQnHirMd8Pz4z/view?usp=sharing" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px; margin-right:8px;">Watch the Talk</a>' +
                        '<a href="assets/docs/HeaLing_Workshop_Presentation.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">View the Slides (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a slide deck and video of my oral talk at the Linguistic Analysis for Health (HeaLing) Workshop at the European Chapter of the Association for Computational Linguistics (EACL) 2026. The presentation covered the findings of my paper \u201cThe Doctor Will Agree With You Now: Sycophancy of Large Language Models in Multi-Turn Medical Conversations\u201d and was one of seven papers selected for oral presentation. It was my first time presenting to a highly specialist academic audience.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Designing for a Specialist Audience</h3>' +
                        '<p>Unlike every other presentation I had given, this talk required me to address a room of researchers who were, in many cases, more expert in the subject matter than I was. That dynamic inverted the communicative challenge I was accustomed to. Rather than translating complex science for non-specialists, I needed to demonstrate that I belonged in the conversation. This meant being precise with terminology, anticipating objections, and signaling familiarity with the field\u2019s existing literature and norms. At the same time, because the HeaLing Workshop sits at the intersection of computational linguistics and healthcare, I could not assume uniform expertise across both domains. Decisions about what to define (e.g., sycophancy, Resistance, the Sticky Incorrect Ratio, etc.) and what to assume were guided by the same principle I had applied in the paper itself: calibrate for the audience most likely to need the explanation without patronizing those who do not.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Rhetorical Choices in Slide Design</h3>' +
                        '<p>A guiding principle throughout the deck was signposting. Each slide title was crafted as a short declarative phrase summarizing the key takeaway, not a topic label like \u201cResults\u201d but a claim like \u201cModels flip correct answers at higher rates than incorrect answers.\u201d This allowed audience members to grasp the argument\u2019s progression even if they momentarily lost the thread of the verbal narration. I also relied on clear definitions at the outset, ensuring that foundational concepts were established before any results were shown so that the data would land with the intended impact rather than requiring the audience to reverse-engineer what was being measured.</p>' +
                        '<p>Balancing text and visuals proved to be an ongoing negotiation. Some slides, particularly those presenting the implications, remain more text-heavy than I would have liked. I attempted to mitigate this by using transitions that revealed bullet points sequentially as I spoke, preventing the audience from reading ahead and losing attention. Feedback I had received during preparation also pushed me in the opposite direction. Several advisors suggested including more on-slide text so that audience members who prefer reading or who are taking notes and miss a verbal point could still follow the argument. Reconciling these competing design philosophies remains something I am still working through, but the experience clarified that slide design is not a neutral formatting exercise. It is a series of rhetorical trade-offs shaped by assumptions about how a specific audience processes information.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Managing Time and Uncertainty</h3>' +
                        '<p>The presentation was allotted fifteen minutes total. I aimed for twelve for the talk and three for questions. Despite multiple practice runs calibrated to that window, I found myself running short on time during the actual delivery and had to compress the implications section, highlighting only the most essential points rather than walking through each one as planned. The experience reinforced a lesson I first encountered when my BIO 176 presentation was cut from ten minutes to five. Adapting to time pressure is not about speaking faster but about being willing to cut, and that willingness must be built into the preparation process rather than improvised in the moment. For future presentations, I plan to build in additional buffer time to account for the small, unpredictable delays (i.e., pausing to gather a thought, responding to an audience member\u2019s body language, adjusting pacing to the room, etc.) that inevitably arise in live delivery.</p>' +
                        '<p>The question-and-answer period introduced a different kind of challenge: the possibility of being asked something I could not answer. I knew I did not need to have an answer to every question, but I still desired to be prepared. As a result, I studied my paper thoroughly and built an appendix into the slide deck containing supplementary figures, model configuration details, and additional analyses that did not fit in the main presentation but could be pulled up if a relevant question arose. This preparation strategy of anticipating the boundaries of what the audience might ask and pre-staging resources to address those questions turned out to be one of the most valuable exercises of the entire process. It was not because every appendix slide was used but because building it forced me to identify and close gaps in my own understanding of the work.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Verbal Delivery as a Communicative Skill</h3>' +
                        '<p>Reviewing my performance afterward, I recognized moments where brief pauses to collect my thoughts or filler words interrupted the flow of the presentation. These are not necessarily unusual in academic talks, but they are worth noting because they represent a dimension of science communication that written artifacts never expose: the challenge of thinking and speaking simultaneously under pressure. The podcast, the YouTube video, and even the picture book all allowed for editing and revision before the audience encountered them. A live oral presentation offers no such luxury. Continuing to improve in this area requires deliberate practice, not just rehearsing content but becoming consciously attuned to verbal habits so that delivery matches the clarity and intentionality of the underlying argument.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This presentation taught me three lessons that deepen my understanding of science communication in high-stakes settings. First, presenting to specialists demands a different kind of rhetorical awareness than presenting to non-specialists. The challenge shifts from translation to credibility, and every design choice, from slide titles to definition placement, signals whether the speaker understands the norms and expectations of the discourse community. Second, time management in live presentations is a communicative skill in its own right. Preparation must account not only for the content but for the unpredictable realities of delivery, and the willingness to cut material on the fly, rather than rush through it, determines whether the audience leaves with a clear argument or a blurred impression. Third, building an appendix is not just a safety net for questions but a preparation methodology that forces the presenter to confront the edges of their own knowledge, and that process of self-interrogation strengthens the entire presentation even if the supplementary material is never shown.</p>',
                    reflection: null,
                    image: null
                },
                {
                    title: "Bio-X Research Poster",
                    thumbnail: 'neanderthal-3',
                    content: '<div style="text-align:center; margin-bottom:1rem;">' +
                        '<img src="' + (typeof EXHIBIT_THUMBNAILS !== 'undefined' && EXHIBIT_THUMBNAILS['neanderthal-3'] ? EXHIBIT_THUMBNAILS['neanderthal-3'] : '') + '" style="max-width:400px; width:100%; border-radius:6px; display:block; margin:0 auto;">' +
                    '</div>' +
                    '<div style="text-align:center; margin-bottom:1.2rem;">' +
                        '<a href="assets/docs/Bio-X_Poster.pdf" target="_blank" rel="noopener" style="display:inline-block; padding:10px 24px; background:#c9a96e; color:#1a1a2e; border-radius:6px; text-decoration:none; font-weight:bold; font-size:14px;">View the Poster (PDF)</a>' +
                    '</div>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
                        '<p>This artifact is a scientific research poster titled \u201cBiventricular Loading During Ex-Vivo Heart Perfusion (EVHP) for Enhanced Functional and Metabolic Assessment of Donor Hearts,\u201d presented at the 2024 Bio-X Interdisciplinary Initiatives Seed Grants Symposium and Poster Session. The work was completed during the summer after my sophomore year as part of the Laboratory for Organ Recovery and Bioengineering at Stanford, where I helped develop a next-generation perfusion system for sustaining explanted pig hearts outside of the body. This was my first experience creating and presenting a technical scientific poster.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Entering a New Genre of Scientific Communication</h3>' +
                        '<p>A research poster occupies a unique communicative space. It must function simultaneously as a standalone document and as a visual aid for live conversation. At the time, I did not fully appreciate that distinction. My approach treated the poster more like a compressed paper than a visual argument, and the result reflects that misunderstanding in ways I can now clearly identify. The experience of standing beside the poster and presenting it to researchers walking through the session taught me something no amount of design advice could have. The poster is not the presentation. The presenter is. Much of the detailed text I had painstakingly fit onto the board went unread while the figures and images that could have anchored the conversation were shrunk to accommodate it.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Lessons in Visual Design and Information Hierarchy</h3>' +
                        '<p>I chose a red and green color scheme to make the poster visually distinctive among rows of conventional designs. While the intent was sound, standing out in a crowded poster session is itself a communicative goal, the execution was somewhat jarring, and the unconventional palette may have distracted from rather than enhanced the scientific content. More significantly, the poster is far too text-heavy. I attempted to include every detail of the methods, results, and background, resulting in small font sizes that discouraged close reading and figures compressed to the point of losing their communicative power. If I were to redesign it, I would cut the text substantially, allow the images (e.g., the transmission electron microscope micrographs, the computational fluid dynamics simulations, and the perfusion system photographs) to occupy more space and do more explanatory work, and include a QR code linking to a more detailed write-up for anyone who wanted more information. The Remotoscope project had already taught me the value of layering explanations for mixed audiences. This poster would have benefited from that same principle, offering a clear visual narrative at a glance with depth available on request.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Structural Gaps</h3>' +
                        '<p>The poster ends abruptly at results, with no discussion, implications, or future work section to contextualize what the findings mean or where the research is headed. This omission was a direct consequence of the space consumed by text elsewhere, a trade-off that, in hindsight, was exactly backwards. A closing section synthesizing the significance of the preliminary loading data and outlining next steps would have given the poster a narrative arc rather than leaving it as a sequence of methods and outcomes. The experience reinforced that even in a highly constrained format, structure matters. A poster, like a paper or a presentation, needs to tell a story with a beginning, middle, and end.</p>' +
                        '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
                        '<p>This project taught me three lessons I have carried into every subsequent piece of scientific communication. First, a poster is a conversation starter, not a self-contained document. The presenter\u2019s voice is the primary medium, and the poster\u2019s job is to provide visual anchors for that conversation rather than to replicate the density of a written report. Second, visual distinctiveness is valuable only when it serves clarity. Design choices like color and layout should draw the viewer toward the content, not compete with it. Third, every communicative format has an information budget, and learning to spend that budget wisely (i.e., prioritizing figures over text, narrative closure over exhaustive detail, etc.) is a skill that improves only through the kind of retrospective honesty this reflection demands.</p>',
                    reflection: null,
                    image: null
                }
            ]
        }
    },

    bambiraptor: {
        title: "<em>Bambiraptor feinbergi</em> Skeleton CAD Model",
        content:
            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Overview</h3>' +
            '<p>This artifact is a computer-aided design (CAD) model of a <em>Bambiraptor feinbergi</em> skeleton created during my senior year of high school for the course Introduction to Engineering Design. The project was open-ended. Students could design anything they wanted using Autodesk Fusion 360, and I chose to reconstruct the skeletal anatomy of a small theropod dinosaur, merging my longstanding interest in paleontology with the engineering design tools and principles we were learning in the course.</p>' +
            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Bridging Science and Engineering Through Design</h3>' +
            '<p>This project marked the first time I brought together two interests that had always felt separate: paleontology and visual design. Prior to this course, my engagement with dinosaurs had been primarily through collecting fossils and consuming scientific literature. Fusion 360 offered something new with the ability to communicate skeletal anatomy not through text or narrative but through a three-dimensional, manipulable object. Modeling each bone required me to study the published literature on <em>Bambiraptor feinbergi</em>, a Late Cretaceous dromaeosaurid discovered in Montana, and translate two-dimensional illustrations and photographs into volumetric forms with accurate proportions and spatial relationships. That translation process was itself an act of scientific communication. It forced me to understand the anatomy deeply enough to reproduce it, revealing gaps in my knowledge that simply reading about the skeleton never would have exposed.</p>' +
            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Learning a New Mode of Communication</h3>' +
            '<p>The course introduced students to the full design process from research and analysis through technical documentation and engineering standards, and working within that framework reshaped how I thought about communicating scientific information. A CAD model is not a paper or a presentation. It is a visual argument about structure. Every decision about how to represent a vertebra, how to articulate the limbs, and how to position the skull communicated something about the organism\u2019s anatomy to anyone who viewed the model. There was no narration or caption to fall back on. The geometry had to speak for itself. This constraint taught me that visual and spatial modes of communication carry their own rhetorical demands, distinct from those of writing or speech, and that accuracy in this genre requires a different kind of rigor, not the rigor of citing sources but of ensuring that every curve and joint reflects what the fossil record actually shows.</p>' +
            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Scientific Accuracy as a Design Challenge</h3>' +
            '<p>One of the most difficult aspects of the project was navigating the uncertainty inherent in paleontological reconstruction. <em>Bambiraptor feinbergi</em> is known from a remarkably complete juvenile specimen, but no fossil preserves every detail of an organism\u2019s skeletal structure. Where published descriptions were ambiguous or where certain elements were incomplete, I had to make informed decisions drawing on comparative anatomy with closely related dromaeosaurids to fill gaps. These choices parallel the interpretive work that paleontologists themselves perform when mounting skeletal reconstructions for museum display, and the process gave me an early appreciation for how scientific visualization always involves a degree of judgment about what to represent, what to infer, and what to leave uncertain.</p>' +
            '<h3 style="color:#c9a96e; margin:0 0 0.5rem;">Key Takeaways</h3>' +
            '<p>This project planted seeds for principles I would continue to develop throughout my ePortfolio. First, scientific communication is not confined to words. A well-constructed visual representation can convey anatomical relationships and structural logic in ways that prose alone cannot, and learning to build in that genre expanded my understanding of what it means to communicate science. Second, the design process itself is a form of inquiry. Modeling each bone required me to interrogate my own understanding of the organism\u2019s anatomy, and the gaps that process revealed made me a more careful reader of the scientific literature. Third, this was my earliest experience combining a personal passion with a disciplinary framework, engineering design, that gave that passion a new communicative outlet, a pattern that would recur in every subsequent project from YouTube videos to interactive simulations to children\u2019s picture books.</p>'
    }
};
